# Use postgres/example user/password credentials
version: '3.9'

services:
  todolist_db:
    container_name: todolist_db 
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "TodoListDb"
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123456"
    ports:
      - 15432:5432
    volumes:
      - ../my-postgres:/var/lib/postgresql/data